// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UISWeb.Data;

namespace UISWeb.Migrations
{
    [DbContext(typeof(UISWebContext))]
    [Migration("20170929065003_UpdateCustomer")]
    partial class UpdateCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UISWeb.Models.Client", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255);

                    b.Property<int>("ClientId");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255);

                    b.Property<string>("ContactName")
                        .HasMaxLength(255);

                    b.HasKey("Email");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("UISWeb.Models.Customer", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255);

                    b.Property<int>("ClientId");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255);

                    b.Property<string>("ContactName")
                        .HasMaxLength(255);

                    b.HasKey("Email");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("UISWeb.Models.CustomerFile", b =>
                {
                    b.Property<string>("FileName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255);

                    b.Property<int>("CustomerRequestLabNo");

                    b.Property<string>("LinkName")
                        .HasMaxLength(255);

                    b.HasKey("FileName");

                    b.HasIndex("CustomerRequestLabNo");

                    b.ToTable("CustomerFile");
                });

            modelBuilder.Entity("UISWeb.Models.CustomerRequest", b =>
                {
                    b.Property<int>("LabNo");

                    b.Property<bool>("Completed");

                    b.Property<string>("Coordinator")
                        .HasMaxLength(100);

                    b.Property<int>("CustomerId");

                    b.Property<string>("Detail")
                        .HasMaxLength(100);

                    b.Property<bool>("Invoiced");

                    b.Property<DateTime>("Received");

                    b.Property<DateTime>("Required");

                    b.HasKey("LabNo");

                    b.ToTable("CustomerRequest");
                });

            modelBuilder.Entity("UISWeb.Models.CustomerFile", b =>
                {
                    b.HasOne("UISWeb.Models.CustomerRequest", "Request")
                        .WithMany("Reports")
                        .HasForeignKey("CustomerRequestLabNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
